profiles:
    __default__:
        koji_config: null
        rpm_koji_target: f$release-flatpak-app
        flatpak_koji_target: f$release-flatpak-candidate
        source_koji_tag: f$release-build
    production:
        koji_profile: koji
    staging:
        koji_profile: staging
