profiles:
    __default__:
        build_source_base: git+https://src.fedoraproject.org
        koji_config: null
        rpm_koji_target: f$release-flatpak-app
        flatpak_koji_target: f$release-flatpak-candidate
        source_koji_tag: f$release-updates-testing-pending
    production:
        koji_profile: koji
    staging:
        koji_profile: stg
